spring.application.name=esiusuarios

server.port=8081

# Configuración de conexión a SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=esiusuarios_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=esiusuarios_app
spring.datasource.password=ds2026
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate: Esto crea las tablas automáticamente por nosotros
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect