spring.application.name=esiusuarios
server.port=8081

# CONFIGURACIÓN SQL SERVER
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=esiusuarios_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=esiusuarios_app
spring.datasource.password=${DB_USUARIOS_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 🔒 SEGURIDAD A02: HARDENING DE CONFIGURACIÓN
# Implementamos la misma política de silencio ante errores para evitar huellas del sistema
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never

# A05: Configuración estricta de JSON - Falla si hay campos que no están en el DTO
spring.jackson.deserialization.fail-on-unknown-properties=true